"""
Enrich KEP features with LLM-generated descriptions and metadata.

Uses Strands Agents SDK to extract structured information from KEP README.md files.

PREFERRED: Use pre-computed metadata from kep_metadata.json (generated by extract-kep-metadata).
FALLBACK: If metadata not found, use LLM to enrich on-the-fly.

Usage:
    uv run k8s-pipeline enrich-features 1.35
    uv run k8s-pipeline enrich-features 1.35 --provider anthropic
    uv run k8s-pipeline enrich-features 1.35 --no-cache  # Force LLM enrichment

What Gets Enriched:
- description: 1-2 sentence summary of what the feature does
- impact: How this affects users/operators
- affectedKinds: Which K8s resource types are affected
- affectedFields: Which API fields are added/modified
- labels: Topic labels for categorization
"""

import json
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

from ...core.config import OUTPUT_DIR, PIPELINE_ROOT
from .parser import KEPS_DIR, Feature, extract_features_for_version
from ..llm_utils import (
    ProviderType,
    UsageTracker,
    create_agent,
    get_effective_model_id,
    get_provider_config,
    get_result_usage,
    load_config,
    log,
)

# Path to pre-computed KEP metadata
KEP_METADATA_PATH = PIPELINE_ROOT / "data" / "curated" / "keps" / "kep_metadata.json"

# Cache for loaded metadata
_kep_metadata_cache: dict[str, Any] | None = None


def load_kep_metadata() -> dict[str, Any]:
    """Load pre-computed KEP metadata from kep_metadata.json."""
    global _kep_metadata_cache
    if _kep_metadata_cache is not None:
        return _kep_metadata_cache

    if not KEP_METADATA_PATH.exists():
        log(f"  [INFO] KEP metadata not found: {KEP_METADATA_PATH}")
        _kep_metadata_cache = {}
        return _kep_metadata_cache

    try:
        with open(KEP_METADATA_PATH) as f:
            _kep_metadata_cache = json.load(f)
        log(f"  [INFO] Loaded metadata for {len(_kep_metadata_cache.get('keps', {}))} KEPs")
        return _kep_metadata_cache
    except Exception as e:
        log(f"  [WARN] Failed to load KEP metadata: {e}")
        _kep_metadata_cache = {}
        return _kep_metadata_cache


def get_kep_metadata(kep_id: str) -> dict[str, Any] | None:
    """Get pre-computed metadata for a specific KEP."""
    metadata = load_kep_metadata()
    return metadata.get("keps", {}).get(kep_id)

# ============================================================================
# Pydantic model for structured output
# ============================================================================


class EnrichedFeature(BaseModel):
    """Structured output for LLM-enriched KEP data."""

    description: str = Field(
        description="1-2 sentence summary of what this feature does and why it matters"
    )
    impact: str = Field(
        description="How this feature affects Kubernetes users and operators"
    )
    affected_kinds: list[str] = Field(
        default_factory=list,
        description="List of Kubernetes resource types affected (e.g., Pod, Deployment, Service)"
    )
    affected_fields: list[str] = Field(
        default_factory=list,
        description="List of API fields added or modified (e.g., spec.containers[].resources.claims)"
    )
    labels: list[str] = Field(
        default_factory=list,
        description="Topic labels for categorization (e.g., numa, cpu-manager, scheduling, networking)"
    )
    suggested_category: str | None = Field(
        default=None,
        description="Suggested category if the current one doesn't fit well"
    )


# ============================================================================
# Helper functions
# ============================================================================


def get_kep_readme(kep_path: str) -> str | None:
    """Read the README.md for a KEP."""
    readme_path = KEPS_DIR / kep_path / "README.md"
    if not readme_path.exists():
        return None

    try:
        content = readme_path.read_text()
        # Truncate very long READMEs to avoid token limits
        if len(content) > 12000:
            content = content[:12000] + "\n\n[... truncated for length ...]"
        return content
    except Exception as e:
        log(f"  [WARN] Failed to read {readme_path}: {e}")
        return None


def create_enrichment_prompt(feature: Feature, readme_content: str) -> str:
    """Create the prompt for enriching a KEP feature."""
    return f"""Analyze this Kubernetes Enhancement Proposal (KEP) and extract metadata.

KEP: {feature.kep} - {feature.title}
SIG: {feature.sig} | Stage: {feature.stage} | Feature Gate: {feature.feature_gate or "None"}
Current Category: {feature.category}

README.md:
---
{readme_content}
---

Extract from the README above:

1. **description**: 1-2 sentence summary of what this feature does and why it matters.

2. **impact**: How this affects Kubernetes users/operators.

3. **affected_kinds**: Kubernetes resource types (Kinds) that have NEW or MODIFIED fields added by this KEP.
   - Only include Kinds where the API schema changes
   - Do NOT include Kinds that are just "used by" or "related to" the feature
   - If this is a kubelet/node config change with no API changes, return empty list

4. **affected_fields**: NEW API fields introduced by this KEP. Use exact field paths from the KEP.
   - Look for Go struct definitions, YAML examples, or "API Changes" sections
   - Use the exact field names shown (e.g., spec.volumes[].image, not spec.volumes[].ociVolumeSource)
   - Only include fields that are NEW, not existing fields that become mutable
   - If this is a kubelet config option (not a Pod/resource API field), return empty list

5. **labels**: Topic labels for cross-referencing and discovery. Extract 2-5 lowercase labels that describe what this KEP is about.
   - IMPORTANT: Use labels from this canonical list whenever applicable:
     security, scheduling, storage, networking, pod, api, node, kubelet, csi, observability,
     feature-gate, cri, kubectl, service, apiserver, configuration, crd, cloud-provider,
     controller, metrics, authentication, performance, volume, validation, autoscaling,
     resource-management, admission, topology, policy, job, kube-proxy, windows, numa,
     cgroups, cpu-manager, dra, dns, deprecation, openapi, statefulset, webhook,
     selinux, apparmor, memory-manager, device-plugin, api-machinery
   - Only invent a new label if nothing in the list above fits
   - Be specific: prefer "cpu-manager" over just "cpu", prefer "traffic-distribution" over just "networking"
   - Include technology-specific terms when relevant (e.g., numa, cgroups, selinux, apparmor)

6. **suggested_category**: The current category is "{feature.category}" (auto-assigned from SIG).
   - If this fits well, return null
   - If a different category would be better, suggest one from: Workloads, Scheduling, Storage, Networking, Security, API, CLI, Observability, Scaling, Platform, Resource Management
   - Only suggest if the current category is clearly wrong

Be precise. Only include what is explicitly defined in the README."""


def _feature_to_dict(feature: Feature) -> dict[str, Any]:
    """Convert Feature dataclass to dict with camelCase keys."""
    return {
        "kep": feature.kep,
        "kepPath": feature.kep_path,
        "title": feature.title,
        "stage": feature.stage,
        "sig": feature.sig,
        "category": feature.category,
        "labels": feature.labels,
        "description": feature.description,
        "impact": feature.impact,
        "featureGate": feature.feature_gate,
        "affectedKinds": feature.affected_kinds,
        "affectedFields": feature.affected_fields,
        "history": feature.history,
    }


# ============================================================================
# Single feature enrichment
# ============================================================================


def enrich_feature_with_llm(
    feature: Feature,
    readme_content: str,
    provider: ProviderType,
    provider_config: dict,
    model_id: str | None = None,
) -> tuple[EnrichedFeature | None, tuple[int, int]]:
    """
    Use LLM to enrich a single feature.

    Returns:
        Tuple of (result, (input_tokens, output_tokens))
    """
    agent = create_agent(
        provider,
        provider_config,
        "You are a Kubernetes expert analyzing KEP documents to extract structured metadata.",
        model_id,
    )

    prompt = create_enrichment_prompt(feature, readme_content)

    try:
        # Use new API: pass structured_output_model to agent invocation
        result = agent(prompt, structured_output_model=EnrichedFeature)
        usage = get_result_usage(result)
        return result.structured_output, usage
    except Exception as e:
        log(f"  [ERROR] LLM enrichment failed for {feature.kep}: {e}")
        return None, (0, 0)


# ============================================================================
# Main enrichment function
# ============================================================================


def enrich_features(
    version: str,
    provider: ProviderType | None = None,
    model_id: str | None = None,
    max_features: int | None = None,
    use_cache: bool = True,
    concurrency: int = 1,
) -> list[dict[str, Any]]:
    """
    Enrich all features for a version with LLM-generated metadata.

    Args:
        version: K8s version (e.g., "1.32")
        provider: Model provider override (uses config file if not specified)
        model_id: Optional specific model ID override
        max_features: Optional limit on features to process (for testing)
        use_cache: If True, use pre-computed metadata from kep_metadata.json
        concurrency: Number of concurrent LLM requests (default: 1 = sequential)

    Returns:
        List of enriched feature dicts
    """
    import concurrent.futures
    import threading

    from ...input.repo_manager import get_current_ref

    config = load_config()
    provider_name, provider_config = get_provider_config(config, provider)
    effective_model_id = get_effective_model_id(provider_config, model_id)

    log(f"\n[ENRICH] Enriching features for Kubernetes {version}")
    log(f"  Provider: {provider_name}, Model: {effective_model_id}")
    log(f"  Use cached metadata: {use_cache}")
    if concurrency > 1:
        log(f"  Concurrency: {concurrency}")

    # Log the current git ref for traceability
    current_ref = get_current_ref("enhancements")
    log(f"  [GIT] enhancements repo at: {current_ref}")

    # Extract base features
    features = extract_features_for_version(version)
    if max_features:
        features = features[:max_features]

    log(f"  Processing {len(features)} features...")

    tracker = UsageTracker(effective_model_id)
    lock = threading.Lock()

    # Pre-process: separate cached vs needs-LLM
    cached_results: list[tuple[int, dict[str, Any]]] = []
    to_process: list[tuple[int, Feature, str]] = []  # (index, feature, readme)

    for i, feature in enumerate(features):
        # Try cache first
        if use_cache:
            cached = get_kep_metadata(feature.kep)
            if cached:
                feature_dict = _feature_to_dict(feature)
                feature_dict["description"] = cached.get("summary", "")
                feature_dict["impact"] = ""
                feature_dict["affectedKinds"] = cached.get("affectedKinds", [])
                feature_dict["affectedFields"] = cached.get("affectedFields", [])
                feature_dict["labels"] = cached.get("labels", [])
                cached_results.append((i, feature_dict))
                continue

        # Need LLM - check for README
        readme = get_kep_readme(feature.kep_path)
        if readme:
            to_process.append((i, feature, readme))
        else:
            # No README, use original
            cached_results.append((i, _feature_to_dict(feature)))

    log(f"  From cache: {len(cached_results)}, Need LLM: {len(to_process)}")

    # Results array (will be filled in order)
    results: dict[int, dict[str, Any]] = {idx: feat for idx, feat in cached_results}
    success_count = 0
    error_count = 0
    processed_count = 0

    def process_feature(item: tuple[int, Feature, str]) -> tuple[int, dict[str, Any] | None, tuple[int, int]]:
        """Process a single feature with LLM."""
        idx, feature, readme = item
        enrichment, usage = enrich_feature_with_llm(
            feature, readme, provider_name, provider_config, model_id  # type: ignore
        )
        if enrichment:
            feature_dict = _feature_to_dict(feature)
            feature_dict["description"] = enrichment.description
            feature_dict["impact"] = enrichment.impact
            feature_dict["affectedKinds"] = enrichment.affected_kinds
            feature_dict["affectedFields"] = enrichment.affected_fields
            feature_dict["labels"] = enrichment.labels
            return idx, feature_dict, usage
        return idx, None, usage

    if to_process:
        with concurrent.futures.ThreadPoolExecutor(max_workers=concurrency) as executor:
            futures = {executor.submit(process_feature, item): item for item in to_process}

            for future in concurrent.futures.as_completed(futures):
                item = futures[future]
                idx, feature, _ = item

                try:
                    result_idx, result_dict, (in_tokens, out_tokens) = future.result()

                    with lock:
                        processed_count += 1
                        tracker.add(in_tokens, out_tokens)

                        if result_dict:
                            results[result_idx] = result_dict
                            success_count += 1
                            log(f"  [{processed_count}/{len(to_process)}] {feature.kep}: [OK]{tracker.format_call(in_tokens, out_tokens)}")
                        else:
                            results[result_idx] = _feature_to_dict(feature)
                            error_count += 1
                            log(f"  [{processed_count}/{len(to_process)}] {feature.kep}: [FAIL]")

                except Exception as e:
                    with lock:
                        processed_count += 1
                        error_count += 1
                        results[idx] = _feature_to_dict(feature)
                        log(f"  [{processed_count}/{len(to_process)}] {feature.kep}: [ERROR] {e}")

    # Build final list in original order
    enriched = [results[i] for i in range(len(features))]

    log(f"\n[DONE] Enriched {len(features)} features")
    log(f"       From cache: {len(cached_results)}")
    log(f"       From LLM: {success_count}")
    log(f"       Errors: {error_count}")

    if tracker.total_input or tracker.total_output:
        log(f"\n[USAGE] {tracker.format_total()}")

    return enriched


def save_enriched_features(version: str, features: list[dict[str, Any]]) -> Path:
    """Save enriched features to a JSON file."""
    output_dir = OUTPUT_DIR / "releases"
    output_path = output_dir / f"{version}-enriched.json"

    output_path.write_text(json.dumps(features, indent=2))
    log(f"  Saved to {output_path}")

    return output_path
